var books = {
    "Pride and Prejudice": [
        "As no objection was made to the young people's engagement with their aunt, and all Mr. Collins's scruples of leaving Mr. and Mrs. Bennet for a single evening during his visit were most steadily resisted, the coach conveyed him and his five cousins at a suitable hour to Meryton; and the girls had the pleasure of hearing, as they entered the drawing-room, that Mr. Wickham had accepted their uncle's invitation, and was then in the house.",
        "Their visits to Mrs. Phillips were now productive of the most interesting intelligence. Every day added something to their knowledge of the officers' names and connections. Their lodgings were not long a secret, and at length they began to know the officers themselves. Mr. Phillips visited them all, and this opened to his nieces a store of felicity unknown before. They could talk of nothing but officers; and Mr. Bingley's large fortune, the mention of which gave animation to their mother, was worthless in their eyes when opposed to the regimentals of an ensign.",
        "They found Mary, as usual, deep in the study of thorough-bass and human nature; and had some extracts to admire, and some new observations of threadbare morality to listen to. Catherine and Lydia had information for them of a different sort. Much had been done and much had been said in the regiment since the preceding Wednesday; several of the officers had dined lately with their uncle, a private had been flogged, and it had actually been hinted that Colonel Forster was going to be married.",
        "After a week spent in professions of love and schemes of felicity, Mr. Collins was called from his amiable Charlotte by the arrival of Saturday. The pain of separation, however, might be alleviated on his side, by preparations for the reception of his bride; as he had reason to hope, that shortly after his return into Hertfordshire, the day would be fixed that was to make him the happiest of men. He took leave of his relations at Longbourn with as much solemnity as before; wished his fair cousins health and happiness again, and promised their father another letter of thanks.",
        "Elizabeth was sitting by herself the next morning, and writing to Jane while Mrs. Collins and Maria were gone on business into the village, when she was startled by a ring at the door, the certain signal of a visitor. As she had heard no carriage, she thought it not unlikely to be Lady Catherine, and under that apprehension was putting away her half-finished letter that she might escape all impertinent questions, when the door opened, and, to her very great surprise, Mr. Darcy, and Mr. Darcy only, entered the room.",
        "When she came to that part of the letter in which her family were mentioned in terms of such mortifying, yet merited reproach, her sense of shame was severe. The justice of the charge struck her too forcibly for denial, and the circumstances to which he particularly alluded as having passed at the Netherfield ball, and as confirming all his first disapprobation, could not have made a stronger impression on his mind than on hers.",
        "They were within twenty yards of each other, and so abrupt was his appearance, that it was impossible to avoid his sight. Their eyes instantly met, and the cheeks of both were overspread with the deepest blush. He absolutely started, and for a moment seemed immovable from surprise; but shortly recovering himself, advanced towards the party, and spoke to Elizabeth, if not in terms of perfect composure, at least of perfect civility.",
        "Their visit did not continue long after the question and answer above mentioned; and while Mr. Darcy was attending them to their carriage Miss Bingley was venting her feelings in criticisms on Elizabeth's person, behaviour, and dress. But Georgiana would not join her. Her brother's recommendation was enough to ensure her favour; his judgement could not err. And he had spoken in such terms of Elizabeth as to leave Georgiana without the power of finding her otherwise than lovely and amiable. When Darcy returned to the saloon, Miss Bingley could not help repeating to him some part of what she had been saying to his sister.",
        "Elizabeth was at no loss to understand from whence this deference to her authority proceeded; but it was not in her power to give any information of so satisfactory a nature as the compliment deserved. She had never heard of his having had any relations, except a father and mother, both of whom had been dead many years. It was possible, however, that some of his companions in the ——shire might be able to give more information; and though she was not very sanguine in expecting it, the application was a something to look forward to.",
        "But the spiritless condition which this event threw her into was shortly relieved, and her mind opened again to the agitation of hope, by an article of news which then began to be in circulation. The housekeeper at Netherfield had received orders to prepare for the arrival of her master, who was coming down in a day or two, to shoot there for several weeks. Mrs. Bennet was quite in the fidgets. She looked at Jane, and smiled and shook her head by turns."
    ],
    "Adventures of Huckleberry Finn": [
        "Now she had got a start, and she went on and told me all about the good place.  She said all a body would have to do there was to go around all day long with a harp and sing, forever and ever.  So I didn't think much of it. But I never said so.  I asked her if she reckoned Tom Sawyer would go there, and she said not by a considerable sight.  I was glad about that, because I wanted him and me to be together.",
        "Ben Rogers said he couldn't get out much, only Sundays, and so he wanted to begin next Sunday; but all the boys said it would be wicked to do it on Sunday, and that settled the thing.  They agreed to get together and fix a day as soon as they could, and then we elected Tom Sawyer first captain and Jo Harper second captain of the Gang, and so started home.",
        "I got a good going-over in the morning from old Miss Watson on account of my clothes; but the widow she didn't scold, but only cleaned off the grease and clay, and looked so sorry that I thought I would behave awhile if I could.  Then Miss Watson she took me in the closet and prayed, but nothing come of it.  She told me to pray every day, and whatever I asked for I would get it.  But it warn't so.  I tried it. Once I got a fish-line, but no hooks.",
        "He said he would like to see the widow get me.  He said he would watch out, and if they tried to come any such game on him he knowed of a place six or seven mile off to stow me in, where they might hunt till they dropped and they couldn't find me.  That made me pretty uneasy again, but only for a minute; I reckoned I wouldn't stay on hand till he got that chance.",
        "I took the axe and smashed in the door.  I beat it and hacked it considerable a-doing it.  I fetched the pig in, and took him back nearly to the table and hacked into his throat with the axe, and laid him down on the ground to bleed; I say ground because it was ground—hard packed, and no boards.  Well, next I took an old sack and put a lot of big rocks in it—all I could drag—and I started it from the pig, and dragged it to the door and through the woods down to the river and dumped it in, and down it sunk, out of sight.",
        "t was the raft, and mighty glad was we to get aboard of it again.  We seen a light now away down to the right, on shore.  So I said I would go for it. The skiff was half full of plunder which that gang had stole there on the wreck.  We hustled it on to the raft in a pile, and I told Jim to float along down, and show a light when he judged he had gone about two mile, and keep it burning till I come; then I manned my oars and shoved for the light.  As I got down towards it three or four more showed—up on a hillside.  It was a village.",
        "Why, that old man kep' up his end in a fight one day for half an hour against three Grangerfords, and come out winner.  They was all a-horseback; he lit off of his horse and got behind a little woodpile, and kep' his horse before him to stop the bullets; but the Grangerfords stayed on their horses and capered around the old man, and peppered away at him, and he peppered away at them.  Him and his horse both went home pretty leaky and crippled, but the Grangerfords had to be fetched home—and one of 'em was dead, and another died the next day.",
        "All the stores was along one street.  They had white domestic awnings in front, and the country people hitched their horses to the awning-posts. There was empty drygoods boxes under the awnings, and loafers roosting on them all day long, whittling them with their Barlow knives; and chawing tobacco, and gaping and yawning and stretching—a mighty ornery lot. They generly had on yellow straw hats most as wide as an umbrella, but didn't wear no coats nor waistcoats, they called one another Bill, and Buck, and Hank, and Joe, and Andy, and talked lazy and drawly, and used considerable many cuss words.",
        "Well, how they all took on!  They crowded around the doctor and tried to quiet him down, and tried to explain to him and tell him how Harvey 'd showed in forty ways that he was Harvey, and knowed everybody by name, and the names of the very dogs, and begged and begged him not to hurt Harvey's feelings and the poor girl's feelings, and all that.  But it warn't no use; he stormed right along, and said any man that pretended to be an Englishman and couldn't imitate the lingo no better than what he did was a fraud and a liar.",
        "But while we was gone for spiders little Thomas Franklin Benjamin Jefferson Elexander Phelps found it there, and opened the door of it to see if the rats would come out, and they did; and Aunt Sally she come in, and when we got back she was a-standing on top of the bed raising Cain, and the rats was doing what they could to keep off the dull times for her.  So she took and dusted us both with the hickry, and we was as much as two hours catching another fifteen or sixteen, drat that meddlesome cub, and they warn't the likeliest, nuther, because the first haul was the pick of the flock."
    ],
    "Alice's Adventures in Wonderland": [
        "Suddenly she came upon a little three-legged table, all made of solid glass; there was nothing on it except a tiny golden key, and Alice's first thought was that it might belong to one of the doors of the hall; but, alas! either the locks were too large, or the key was too small, but at any rate it would not open any of them. However, on the second time round, she came upon a low curtain she had not noticed before, and behind it was a little door about fifteen inches high: she tried the little golden key in the lock, and to her great delight it fitted!",
        "As she said this she looked down at her hands, and was surprised to see that she had put on one of the Rabbit's little white kid gloves while she was talking. 'How can I have done that?' she thought. 'I must be growing small again.' She got up and went to the table to measure herself by it, and found that, as nearly as she could guess, she was now about two feet high, and was going on shrinking rapidly: she soon found out that the cause of this was the fan she was holding, and she dropped it hastily, just in time to avoid shrinking away altogether.",
        "Alas! it was too late to wish that! She went on growing, and growing, and very soon had to kneel down on the floor: in another minute there was not even room for this, and she tried the effect of lying down with one elbow against the door, and the other arm curled round her head. Still she went on growing, and, as a last resource, she put one arm out of the window, and one foot up the chimney, and said to herself 'Now I can do no more, whatever happens.",
        "The great question certainly was, what? Alice looked all round her at the flowers and the blades of grass, but she did not see anything that looked like the right thing to eat or drink under the circumstances. There was a large mushroom growing near her, about the same height as herself; and when she had looked under it, and on both sides of it, and behind it, it occurred to her that she might as well look and see what was on the top of it.",
        "As there seemed to be no chance of getting her hands up to her head, she tried to get her head down to them, and was delighted to find that her neck would bend about easily in any direction, like a serpent. She had just succeeded in curving it down into a graceful zigzag, and was going to dive in among the leaves, which she found to be nothing but the tops of the trees under which she had been wandering, when a sharp hiss made her draw back in a hurry: a large pigeon had flown into her face, and was beating her violently with its wings.",
        "The King and Queen of Hearts were seated on their throne when they arrived, with a great crowd assembled about them—all sorts of little birds and beasts, as well as the whole pack of cards: the Knave was standing before them, in chains, with a soldier on each side to guard him; and near the King was the White Rabbit, with a trumpet in one hand, and a scroll of parchment in the other.",
        "'Oh, I've had such a curious dream!' said Alice, and she told her sister, as well as she could remember them, all these strange Adventures of hers that you have just been reading about; and when she had finished, her sister kissed her, and said, 'It was a curious dream, dear, certainly: but now run in to your tea; it's getting late.' So Alice got up and ran off, thinking while she ran, as well she might, what a wonderful dream it had been.",
        "The baby grunted again, and Alice looked very anxiously into its face to see what was the matter with it. There could be no doubt that it had a very turn-up nose, much more like a snout than a real nose; also its eyes were getting extremely small for a baby: altogether Alice did not like the look of the thing at all. 'But perhaps it was only sobbing,' she thought, and looked into its eyes again, to see if there were any tears.",
        "It was so long since she had been anything near the right size, that it felt quite strange at first; but she got used to it in a few minutes, and began talking to herself, as usual. 'Come, there's half my plan done now! How puzzling all these changes are! I'm never sure what I'm going to be, from one minute to another! However, I've got back to my right size: the next thing is, to get into that beautiful garden—how is that to be done, I wonder?' As she said this, she came suddenly upon an open place, with a little house in it about four feet high.",
        "The great question certainly was, what? Alice looked all round her at the flowers and the blades of grass, but she did not see anything that looked like the right thing to eat or drink under the circumstances. There was a large mushroom growing near her, about the same height as herself; and when she had looked under it, and on both sides of it, and behind it, it occurred to her that she might as well look and see what was on the top of it."
    ],
    "Metamorphosis": [
        "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked.",
        "The first thing he wanted to do was get the lower part of his body out of the bed, but he had never seen this lower part, and could not imagine what it looked like; it turned out to be too hard to move; it went so slowly; and finally, almost in a frenzy, when he carelessly shoved himself forwards with all the force he could gather, he chose the wrong direction, hit hard against the lower bedpost, and learned from the burning pain he felt that the lower part of his body might well, at present, be the most sensitive.",
        "And while Gregor gushed out these words, hardly knowing what he was saying, he made his way over to the chest of drawers - this was easily done, probably because of the practise he had already had in bed - where he now tried to get himself upright. He really did want to open the door, really did want to let them see him and to speak with the chief clerk; the others were being so insistent, and he was curious to learn what they would say when they caught sight of him. If they were shocked then it would no longer be Gregor's responsibility and he could rest.",
        "So Gregor did not go into the room, but leant against the inside of the other door which was still held bolted in place. In this way only half of his body could be seen, along with his head above it which he leant over to one side as he peered out at the others. Meanwhile the day had become much lighter; part of the endless, grey-black building on the other side of the street - which was a hospital - could be seen quite clearly with the austere and regular line of windows piercing its façade; the rain was still falling, now throwing down large, individual droplets which hit the ground one at a time.",
        "It was not until it was getting dark that evening that Gregor awoke from his deep and coma-like sleep. He would have woken soon afterwards anyway even if he hadn't been disturbed, as he had had enough sleep and felt fully rested. But he had the impression that some hurried steps and the sound of the door leading into the front room being carefully shut had woken him. The light from the electric street lamps shone palely here and there onto the ceiling and tops of the furniture, but down below, where Gregor was, it was dark.",
        "Gregor soon had the opportunity to test the strength of his decisions, as early the next morning, almost before the night had ended, his sister, nearly fully dressed, opened the door from the front room and looked anxiously in. She did not see him straight away, but when she did notice him under the couch - he had to be somewhere, for God's sake, he couldn't have flown away - she was so shocked that she lost control of herself and slammed the door shut again from outside.",
        "That was the sort of totally pointless thing that went through his mind in his present state, pressed upright against the door and listening. There were times when he simply became too tired to continue listening, when his head would fall wearily against the door and he would pull it up again with a start, as even the slightest noise he caused would be heard next door and they would all go silent. 'What's that he's doing now', his father would say after a while, clearly having gone over to the door, and only then would the interrupted conversation slowly be taken up again.",
        "For the first fourteen days, Gregor's parents could not bring themselves to come into the room to see him. He would often hear them say how they appreciated all the new work his sister was doing even though, before, they had seen her as a girl who was somewhat useless and frequently been annoyed with her. But now the two of them, father and mother, would often both wait outside the door of Gregor's room while his sister tidied up in there, and as soon as she went out again she would have to tell them exactly how everything looked, what Gregor had eaten, how he had behaved this time and whether, perhaps, any slight improvement could be seen. ",
        "Hearing these words from his mother made Gregor realise that the lack of any direct human communication, along with the monotonous life led by the family during these two months, must have made him confused - he could think of no other way of explaining to himself why he had seriously wanted his room emptied out. Had he really wanted to transform his room into a cave, a warm room fitted out with the nice furniture he had inherited? That would have let him crawl around unimpeded in any direction, but it would also have let him quickly forget his past when he had still been human.",
        "Because of his injuries, Gregor had lost much of his mobility - probably permanently. He had been reduced to the condition of an ancient invalid and it took him long, long minutes to crawl across his room - crawling over the ceiling was out of the question - but this deterioration in his condition was fully (in his opinion) made up for by the door to the living room being left open every evening. He got into the habit of closely watching it for one or two hours before it was opened and then, lying in the darkness of his room where he could not be seen from the living room, he could watch the family in the light of the dinner table and listen to their conversation - with everyone's permission, in a way, and thus quite differently from before."
    ],
    "A Tale of Two Cities": [
        "It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations were conceded to England at that favoured period, as at this. Mrs. Southcott had recently attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards had heralded the sublime appearance by announcing that arrangements were made for the swallowing up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of years, after rapping out its messages, as the spirits of this very year last past (supernaturally deficient in originality) rapped out theirs.",
        "Two other passengers, besides the one, were plodding up the hill by the side of the mail. All three were wrapped to the cheekbones and over the ears, and wore jack-boots. Not one of the three could have said, from anything he saw, what either of the other two was like; and each was hidden under almost as many wrappers from the eyes of the mind, as from the eyes of the body, of his two companions. In those days, travellers were very shy of being confidential on a short notice, for anybody on the road might be a robber or in league with robbers.",
        "His message perplexed his mind to that degree that he was fain, several times, to take off his hat to scratch his head. Except on the crown, which was raggedly bald, he had stiff, black hair, standing jaggedly all over it, and growing down hill almost to his broad, blunt nose. It was so like Smith's work, so much more like the top of a strongly spiked wall than a head of hair, that the best of players at leap-frog might have declined him, as the most dangerous man in the world to go over.",
        "A shrill sound of laughter and of amused voices—voices of men, women, and children—resounded in the street while this wine game lasted. There was little roughness in the sport, and much playfulness. There was a special companionship in it, an observable inclination on the part of every one to join some other one, which led, especially among the luckier or lighter-hearted, to frolicsome embraces, drinking of healths, shaking of hands, and even joining of hands and dancing, a dozen together. When the wine was gone, and the places where it had been most abundant were raked into a gridiron-pattern by fingers, these demonstrations ceased, as suddenly as they had broken out.",
        "Such a staircase, with its accessories, in the older and more crowded parts of Paris, would be bad enough now; but, at that time, it was vile indeed to unaccustomed and unhardened senses. Every little habitation within the great foul nest of one high building—that is to say, the room or rooms within every door that opened on the general staircase—left its own heap of refuse on its own landing, besides flinging other refuse from its own windows.",
        "But not for long. Releasing his arm, she laid her hand upon his shoulder. After looking doubtfully at it, two or three times, as if to be sure that it was really there, he laid down his work, put his hand to his neck, and took off a blackened string with a scrap of folded rag attached to it. He opened this, carefully, on his knee, and it contained a very little quantity of hair: not more than one or two long golden hairs, which he had, in some old day, wound off upon his finger.",
        "They hanged at Tyburn, in those days, so the street outside Newgate had not obtained one infamous notoriety that has since attached to it. But, the gaol was a vile place, in which most kinds of debauchery and villainy were practised, and where dire diseases were bred, that came into court with the prisoners, and sometimes rushed straight from the dock at my Lord Chief Justice himself, and pulled him off the bench. It had more than once happened, that the Judge in the black cap pronounced his own doom as certainly as the prisoner's, and even died before him.",
        "There ought to have been a tranquil bark in such an anchorage, and there was. The Doctor occupied two floors of a large stiff house, where several callings purported to be pursued by day, but whereof little was audible any day, and which was shunned by all of them at night. In a building at the back, attainable by a courtyard where a plane-tree rustled its green leaves, church-organs claimed to be made, and silver to be chased, and likewise gold to be beaten by some mysterious giant who had a golden arm starting out of the wall of the front hall—as if he had beaten himself precious, and menaced a similar conversion of all visitors.",
        "The sweet scents of the summer night rose all around him, and rose, as the rain falls, impartially, on the dusty, ragged, and toil-worn group at the fountain not far away; to whom the mender of roads, with the aid of the blue cap without which he was nothing, still enlarged upon his man like a spectre, as long as they could bear it. By degrees, as they could bear no more, they dropped off one by one, and lights twinkled in little casements; which lights, as the casements darkened, and more stars came out, seemed to have shot up into the sky instead of having been extinguished.",
        "With his straw in his mouth, Mr. Cruncher sat watching the two streams, like the heathen rustic who has for several centuries been on duty watching one stream—saving that Jerry had no expectation of their ever running dry. Nor would it have been an expectation of a hopeful kind, since a small part of his income was derived from the pilotage of timid women (mostly of a full habit and past the middle term of life) from Tellson's side of the tides to the opposite shore."
    ],
    "Dracula": [
        "I did not sleep well, though my bed was comfortable enough, for I had all sorts of queer dreams. There was a dog howling all night under my window, which may have had something to do with it; or it may have been the paprika, for I had to drink up all the water in my carafe, and was still thirsty. Towards morning I slept and was wakened by the continuous knocking at my door, so I guess I must have been sleeping soundly then.",
        "At last there came a time when the driver went further afield than he had yet gone, and during his absence, the horses began to tremble worse than ever and to snort and scream with fright. I could not see any cause for it, for the howling of the wolves had ceased altogether; but just then the moon, sailing through the black clouds, appeared behind the jagged crest of a beetling, pine-clad rock, and by its light I saw around us a ring of wolves, with white teeth and lolling red tongues, with long, sinewy limbs and shaggy hair.",
        "Presently, with an excuse, he left me, asking me to put all my papers together. He was some little time away, and I began to look at some of the books around me. One was an atlas, which I found opened naturally at England, as if that map had been much used. On looking at it I found in certain places little rings marked, and on examining these I noticed that one was near London on the east side, manifestly where his new estate was situated; the other two were Exeter, and Whitby on the Yorkshire coast.",
        "I was not alone. The room was the same, unchanged in any way since I came into it; I could see along the floor, in the brilliant moonlight, my own footsteps marked where I had disturbed the long accumulation of dust. In the moonlight opposite me were three young women, ladies by their dress and manner. I thought at the time that I must be dreaming when I saw them, for, though the moonlight was behind them, they threw no shadow on the floor. They came close to me, and looked at me for some time, and then whispered together. ",
        "At one corner of the room was a heavy door. I tried it, for, since I could not find the key of the room or the key of the outer door, which was the main object of my search, I must make further examination, or all my efforts would be in vain. It was open, and led through a stone passage to a circular stairway, which went steeply down. I descended, minding carefully where I went, for the stairs were dark, being only lit by loopholes in the heavy masonry. At the bottom there was a dark, tunnel-like passage, through which came a deathly, sickly odour, the odour of old earth newly turned. As I went through the passage the smell grew closer and heavier.",
        "Lucy met me at the station, looking sweeter and lovelier than ever, and we drove up to the house at the Crescent in which they have rooms. This is a lovely place. The little river, the Esk, runs through a deep valley, which broadens out as it comes near the harbour. A great viaduct runs across, with high piers, through which the view seems somehow further away than it really is. The valley is beautifully green, and it is so steep that when you are on the high land on either side you look right across it, unless you are near enough to see down. The houses of the old town—the side away from us—are all red-roofed, and seem piled up one over the other anyhow, like the pictures we see of Nuremberg.",
        "Another bad night. Mother did not seem to take to my proposal. She seems not too well herself, and doubtless she fears to worry me. I tried to keep awake, and succeeded for a while; but when the clock struck twelve it waked me from a doze, so I must have been falling asleep. There was a sort of scratching or flapping at the window, but I did not mind it, and as I remember no more, I suppose I must then have fallen asleep. More bad dreams. I wish I could remember them. This morning I am horribly weak.",
        "He did not remain long, but said he would look in later in the day and see Lord Godalming. His coming, however, had been a certain comfort to us, since it assured us that we should not have to dread hostile criticism as to any of our acts. Arthur was expected at five o’clock, so a little before that time we visited the death-chamber. It was so in very truth, for now both mother and daughter lay in it. The undertaker, true to his craft, had made the best display he could of his goods, and there was a mortuary air about the place that lowered our spirits at once.",
        "Jonathan is better after a bad night. I am so glad that he has plenty of work to do, for that keeps his mind off the terrible things; and oh, I am rejoiced that he is not now weighed down with the responsibility of his new position. I knew he would be true to himself, and now how proud I am to see my Jonathan rising to the height of his advancement and keeping pace in all ways with the duties that come upon him. He will be away all day till late, for he said he could not lunch at home.",
        "We could not see the face, for it was bent down over what we saw to be a fair-haired child. There was a pause and a sharp little cry, such as a child gives in sleep, or a dog as it lies before the fire and dreams. We were starting forward, but the Professor’s warning hand, seen by us as he stood behind a yew-tree, kept us back; and then as we looked the white figure moved forwards again. It was now near enough for us to see clearly, and the moonlight still held. My own heart grew cold as ice, and I could hear the gasp of Arthur, as we recognised the features of Lucy Westenra."
    ]
};
var n = 4;
var b = "Pride and Prejudice";

$("#paragraphNumber").keypress(function(e) {
    if (e.which == 10 || e.which == 13) { // If enter key pressed, simulate submission
        $(this).submit();
    }
});

$("#paragraphNumber").submit(function() {
    var val = parseInt($(this).val());
    if (val >= 1 && val <= 50) {
        n = val;
        updateLipsum();
    } else {
        alert("Please enter a number between 1 and 50 inclusive.");
    }
});

$("#lipsum__container li").click(function() {
    if (!$(this).hasClass("selected")) {
        $(".selected").removeClass("selected");
        $(this).addClass("selected");
        b = $(this).html().replace(/ <span class="book__author">(.*)<\/span>/, "");
        updateLipsum();
    }
});

function updateLipsum() {
    var text = "";
    for (var i = 1; i <= n; i++) {
        text += "<p>" + books[b][(i % 10) - 1] + "</p>\r\n";
    }
    $("#lipsum__text").val(text);
    $("#lipsum__text").select();
}